### ISSUE TITLE
Unable to build on Windows 11 

### ISSUE THREAD

**Issue by pvsvamsi** [BestOwl/MyPhone#10]
I have tried these steps,

![image](https://user-images.githubusercontent.com/20770470/165309225-fc19b589-bdc0-417d-b40f-85c262d2bd12.png)

Getting this error

MSB4018: The task failed unexpectedly

![image](https://user-images.githubusercontent.com/20770470/165310343-c53d82ea-aabd-49ab-a23d-1b2bdc7ee9a7.png)

Can you please help me with the steps to resolve this?

**Comment by pvsvamsi** [comment]
I have retargetted the solution to the latest versions and got into this error now

![image](https://user-images.githubusercontent.com/20770470/165311775-9a065c42-ece1-422e-ba1f-9c7a67485878.png)

**Comment by BestOwl** [comment]
What version of Visual Studio are you using? It might be related to #8
The current packaging method is a little bit tricky, so the latest version of Visual Studio might not work.
Last tested working Visual Studio versions are v16.9 and v17.0 (preview 4.1)

I am recently working on #9, which will refactor the project into a single Win32 app and solve #8.

**Comment by pvsvamsi** [comment]
@BestOwl Thank you for the update. Any timeline for [#9 ](https://github.com/BestOwl/MyPhone/issues/9)?
Also I want to contribute to this repo, any guidelines or documentations to begin with?

**Comment by BestOwl** [comment]
> @BestOwl Thank you for the update. Any timeline for [#9 ](https://github.com/BestOwl/MyPhone/issues/9)? Also I want to contribute to this repo, any guidelines or documentations to begin with?

I will try to prepare some documents tonight.

**Comment by BestOwl** [comment]
For #9, maybe mid June.

**Comment by BestOwl** [comment]
@pvsvamsi I just updated the README in the `9-win-app-sdk` branch, you may now follow the guide to build this project.

**Comment by pvsvamsi** [comment]
@BestOwl I'm getting this error now
![image](https://user-images.githubusercontent.com/20770470/168008992-f75ab7bf-74e6-43b3-8840-bca09cdbfd3d.png)

**Comment by BestOwl** [comment]
You need to install the single project MSIX VS extension
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp#install-the-single-project-msix-packaging-tools

**Comment by pvsvamsi** [comment]
@BestOwl It's working now. Thank you

**Comment by BestOwl** [comment]
> For #9, maybe mid June.

Forget about this timeline. I spent some time working on this over the past few days. By now, all existing features from the original UWP app have been implemented.

**Comment by BestOwl** [comment]
Since the problem has been resolved, this issue will be closed.

BTW, I just added a GitHub Action CI to ensure the app can be built successfully.

**Comment by pvsvamsi** [comment]
1. Call functionality is not working from the UI (tried from Call tab, Debug mode) with ios 15.4.1
2. How to generate the executable file from this repo?

**Comment by BestOwl** [comment]
In debug mode, do you see any phone line GUIDs?
![image](https://user-images.githubusercontent.com/8947026/168560254-1534f45b-5600-4f92-a0da-3b9254923bc3.png)

If so, please select one, and then press the call button below

**Comment by BestOwl** [comment]
When you build, executable will be generated in `MyPhone\bin\x64\Release\net6.0-windows10.0.19041.0\win10-x64`.
However, you can not launch the executable directly because WinUI 3 apps currently need to run inside the MSIX app container.

**Comment by pvsvamsi** [comment]
> In debug mode, do you see any phone line GUIDs? ![image](https://user-images.githubusercontent.com/8947026/168560254-1534f45b-5600-4f92-a0da-3b9254923bc3.png)
> 
> If so, please select one, and then press the call button below

I'm not able to see any phone line GUIDs

**Comment by pvsvamsi** [comment]
> In debug mode, do you see any phone line GUIDs? ![image](https://user-images.githubusercontent.com/8947026/168560254-1534f45b-5600-4f92-a0da-3b9254923bc3.png)
> 
> If so, please select one, and then press the call button below

Not it's not visible. But call are getting connected from the PC if directly initiated from the mobile

**Comment by pvsvamsi** [comment]
> When you build, executable will be generated in `MyPhone\bin\x64\Release\net6.0-windows10.0.19041.0\win10-x64`. However, you can not launch the executable directly because WinUI 3 apps currently need to run inside the MSIX app container.

Any other way to share the build with other pc?

**Comment by BestOwl** [comment]
To share a build with other PC, you have two options:
1. In Visual Studio, right click the `MyPhone` project, then click **Package and Publish > Create App Packages**
2. Download CI build directly from Github Action in this repo. For example, open the latest action run here https://github.com/BestOwl/MyPhone/actions/runs/2324753782, then scroll down to the bottom and download the artifact 
![image](https://user-images.githubusercontent.com/8947026/169299686-93cc2085-4bfa-4ce5-8854-87dc62934063.png)

**Comment by BestOwl** [comment]
@pvsvamsi Sorry, I didn't have time to provide a complete contributing guideline and document, I am currently busy working on the first beta release. Anyway, which feature would you like to contribute? If you have any questions regarding contributing, I can answer them right now.

**Comment by pvsvamsi** [comment]
@BestOwl I don't have experience in developing windows applications. Can you point me towards starter guides for the same?

**Comment by BestOwl** [comment]
@pvsvamsi You will need to learn the following to get started:
1. C#
2. WinUI 3 / XAML 
Here is a book https://www.packtpub.com/product/learn-winui-3-0/9781800208667
You can also refer to UWP, WPF, or Xamarin guide because they use similar XAML to create UI.
3. MVVM pattern
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/mvvm
