### ISSUE TITLE
Not able to run the sample on windows 10 desktop

### ISSUE THREAD

**Issue by hpxiong** [BestOwl/MyPhone#2]
Is there step missing to have this run on regular windows desktop?

According to MS, PhoneLineTransportDevice class only applies to WinRT Build 18362, Build 19041, Build 20348, Build 22000 (Preview)
https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.calls.phonelinetransportdevice?view=winrt-20348

Not Implemented exception was thrown here: 

Feature com.microsoft.windows.applicationmodel.phonelinetransportdevice_v1 is not available
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
   at Windows.ApplicationModel.Calls.PhoneLineTransportDevice.GetDeviceSelector(PhoneLineTransport transport)
   at GoodTimeStudio.MyPhone.Models.BluetoothDeviceListViewModel..ctor() in C:\repos\MyPhone\MyPhone\Models\BluetoothDeviceListViewModel.cs:line 28
   at GoodTimeStudio.MyPhone.BluetoothDeviceListView..ctor() in C:\repos\MyPhone\MyPhone\BluetoothDeviceListView.xaml.cs:line 29

**Comment by hpxiong** [comment]
I updated the device query to use: BluetoothDevice.GetDeviceSelectorFromPairingState(true) and this works for getting the BT device list. But now the problem is the following statement never comes back in DeviceManager.

await App.SendRequest("goodtimestudio.myphone.trayapp://connect/" + deviceInfo.Id);

-- is this the right way to connect to BT devices? Your MAP demo uses Socket to connect though.

**Comment by hpxiong** [comment]
While debugging, the program never seems to be able to hit Connect method inside MyPhone.TrayApp BackgroundServer.cpp. Instead the console says:

The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[32716] MyPhone.TrayApp.exe' has exited with code 0 (0x0).

Any suggestions??

**Comment by BestOwl** [comment]
It should work on Windows 10 Version 1903 (build 18362) and above. I tested again on Windows 11 (build 22000), and it works fine. What‘s your OS version?

**Comment by BestOwl** [comment]
You can't change the device query to BluetoothDevice.GetDeviceSelectorFromPairingState(true) because `BluetoothDevice` and `PhoneLineTransportDevice` have different device id. 
![image](https://user-images.githubusercontent.com/8947026/128291668-7b831b64-f24d-4624-94d0-f4af692110a1.png)

https://github.com/BestOwl/MyPhone/blob/9cb86e823e6932e8fce70c4eee34e2f895cd96a4/MyPhone.TrayApp/BackgroundServer.cpp#L144-L156

The Connect method in BackgroundServer.cpp use `PhoneLineTransportDevice::FromId()` which requires a PhoneLineTransportDeviceId as input.

**Comment by hpxiong** [comment]
@BestOwl  Thank you for the reply. 

My system info: 

![image](https://user-images.githubusercontent.com/17347604/128295558-3565b5e8-85a4-438d-a52e-607423098b34.png)

Here is the exception I ran into 

![image](https://user-images.githubusercontent.com/17347604/128295527-8529af7d-d253-4976-b791-37546fbb34a3.png)

I see quite a lot WinRT originator errors:

'MyPhone.exe' (Win32): Loaded 'C:\Windows\System32\PhoneOm.dll'. Symbols loaded.
'MyPhone.exe' (Win32): Loaded 'C:\Windows\System32\Phoneutil.dll'. Symbols loaded.
Exception thrown at 0x00007FFB828B3FE9 (KernelBase.dll) in MyPhone.exe: **WinRT originate error** - 0x80040111 : 'Windows.ApplicationModel.LimitedAccessFeatures'.
onecore\com\combase\winrt\error\restrictederror.cpp(1014)\combase.dll!00007FFB82DEDD50: (caller: 00007FFB82D90D8C) ReturnHr(1) tid(7228) 8007007E The specified module could not be found.
Exception thrown at 0x00007FFB828B3FE9 (KernelBase.dll) in MyPhone.exe: **WinRT originate error** - 0x80004001 : 'Feature com.microsoft.windows.applicationmodel.phonelinetransportdevice_v1 is not available'.
onecore\com\combase\winrt\error\restrictederror.cpp(1014)\combase.dll!00007FFB82DEDD50: (caller: 00007FFB82D90D8C) ReturnHr(2) tid(7228) 8007007E The specified module could not be found.
onecoreuap\net\phone\phoneom\winrt\phonelinetransportdevicestatics.cpp(31)\PhoneOm.dll!00007FFB7D890FC1: (caller: 00007FFB7D8912AE) ReturnHr(1) tid(7228) 80004001 Not implemented
onecoreuap\net\phone\phoneom\winrt\phonelinetransportdevicestatics.cpp(108)\PhoneOm.dll!00007FFB7D8912CD: (caller: 00007FFA8F791AD1) ReturnHr(2) tid(7228) 80004001 Not implemented
Exception thrown: 'System.NotImplementedException' in MyPhone.exe
An exception of type 'System.NotImplementedException' occurred in MyPhone.exe but was not handled in user code
Not implemented

Feature com.microsoft.windows.applicationmodel.phonelinetransportdevice_v1 is not available

**Comment by BestOwl** [comment]
Very strange, seems like 18363 doesn't support this API. I'm trying to install build 18363 and test it on my machine.

**Comment by hpxiong** [comment]
I tested again on another Windows 10 Pro and it worked this time. Not sure if it is due to Windows 10 Enterprise or special policy that prevents the access to certain library in Windows.ApplicationModel namespace. 

I'm curious what is the status with SMS Message implementation. any code base to share? I'm interested in contributing. Thanks!

**Comment by BestOwl** [comment]
The MAP demo at https://github.com/BestOwl/MyPhone/blob/master/MyPhone.Demo/MAP.cs can now establish the MAS/MNS service connection and get the message info whenever a new SMS message arrived.  What we need to do next is to implement a UI and register it as a UWP background service.

**Comment by BestOwl** [comment]
Glad to hear you are interested in this project btw, welcome aboard :)

**Comment by hpxiong** [comment]
@BestOwl  I will check out the SMS code. Thanks! 
If you find out more on the original problem on the "WinRT originator error", "Not implemented exception", please share it here. Since the code works in another system, I will close this issue for now.
